# Audit4j build and test via Travis-CI

language: java

jdk:
 - oraclejdk7
 - openjdk7
 
script: mvn clean install -DskipTests=true -Dgpg.skip=true

notifications:
  email:
    recipients:
      - janith@audit4j.org