!ServerConfiguration
transports: 
- !org.audit4j.microservice.transport.thrift.ThriftTransportServer {} #Transport via websocket: Default port 9092
- !org.audit4j.microservice.transport.WebSocketTransportServer {} #Transport via websocket: Default port 9091
